stages:
  - source-scan
  - deploy-ecr-prod
  - deploy-ecr-carbon-prod
  - deploy-cdk-prod-MartinEoapiStack
  - deploy-cdk-carbon-prod-MartinEoapiStack
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

source-code-scan:
  stage: source-scan
  tags:
    - docker-runner
  image: sonarsource/sonar-scanner-cli:latest
  only:
    - master
  script:
    - sonar-scanner -Dsonar.projectKey=${CI_PROJECT_NAMESPACE}--${CI_PROJECT_NAME} -Dsonar.sources=. -Dsonar.host.url=https://madrid.thaicom.io/sonar  -Dsonar.login=$SONAR_ID

deploy_ecr_prod:
  stage: deploy-ecr-prod
  tags:
    - docker-runner
  when: manual
  image: docker:24.0.5
  # image: ubuntu-2204:2022.04.2
  services:
    - name: docker:24.0.5-dind
      alias: docker
  only:
    - master
  variables:
    ECR_NAME: martin-eoapi-prod
    ECR_TAG: latest
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PROD}
    - export AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID_PROD}
    - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - docker info
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
    - aws ecr describe-repositories --repository-names ${ECR_NAME} || aws ecr create-repository --repository-name ${ECR_NAME}
    - aws --version
    - docker --version
  script:
    - cd dependencies/docker
    - cp config.yaml.prod config.yaml
    - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_NAME}:${ECR_TAG} .
    - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_NAME}:${ECR_TAG}

deploy_ecr_carbon_prod:
  stage: deploy-ecr-carbon-prod
  tags:
    - docker-runner
  when: manual
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  only:
    - master
  variables:
    ECR_NAME: martin-eoapi-prod
    ECR_TAG: latest
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_CARBON_PROD}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_CARBON_PROD}
    - export AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID_CARBON_PROD}
    - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - docker info
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
    - aws ecr describe-repositories --repository-names ${ECR_NAME} || aws ecr create-repository --repository-name ${ECR_NAME}
    - aws --version
    - docker --version
  script:
    - cd dependencies/docker
    - cp config.yaml.carbon-prod config.yaml
    - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_NAME}:${ECR_TAG} .
    - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_NAME}:${ECR_TAG}


deploy_cdk_prod_MartinEoapiStack:
  stage: deploy-cdk-prod-MartinEoapiStack
  tags:
    - docker-runner
  when: manual
  image: rome.thaicom.io/aws-cdk-python:2.95.1
  only:
    - master
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PROD}
    - export AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID_PROD}
    - cp $ENV_FILE_PROD .env
    - export ENV_FILE_PATH=.env
    - cdk --version
  script:
    - echo deploy_cdk_prod
    - python -m pip install -r requirements.txt
    - cdk bootstrap aws://${AWS_ACCOUNT_ID_PROD}/${AWS_DEFAULT_REGION}
    - cdk deploy --require-approval never MartinEoapiStack

deploy_cdk_prod_carbon_MartinEoapiStack:
  stage: deploy-cdk-carbon-prod-MartinEoapiStack
  tags:
    - docker-runner
  when: manual
  image: rome.thaicom.io/aws-cdk-python:2.95.1
  only:
    - master
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_CARBON_PROD}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_CARBON_PROD}
    - export AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID_CARBON_PROD}
    - cp $ENV_FILE_CARBON_PROD .env
    - export ENV_FILE_PATH=.env
    - cdk --version
    - cat .env
  script:
    - echo deploy_cdk_prod
    - python -m pip install -r requirements.txt
    # - cdk bootstrap aws://${AWS_ACCOUNT_ID_CARBON_PROD}/${AWS_DEFAULT_REGION}
    - cdk synth
    - cdk deploy --require-approval never MartinEoapiStack